### ISSUE TITLE
Error: Make sure to install japa before running tests. npm i --save-dev japa

### ISSUE THREAD

**Issue by kamerk22** [thetutlage/japa-cli#1]
`japa` is alrady install as `devDependencies` . Error is coming from `RunCommand.js:116:15`  which is `_requireJapaCli` method

`Error: Make sure to install japa before running tests. npm i --save-dev japa`

**Comment by thetutlage** [comment]
Japa cli is not required with the newer versions of Japa. Simply run you tests by saying `node japaFile.js` and it will execute all the tests

**Comment by kamerk22** [comment]
@thetutlage fixed!
